"""menambahkan tabel transaksi

Revision ID: 2d192be4422e
Revises: dda76804e5a4
Create Date: 2026-05-22 01:46:54.518350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d192be4422e'
down_revision = 'dda76804e5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesanan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('id_alamat', sa.String(length=36), nullable=True),
    sa.Column('id_promo', sa.String(length=36), nullable=True),
    sa.Column('tanggal_pesan', sa.DateTime(), nullable=True),
    sa.Column('tanggal_pengiriman', sa.Date(), nullable=False),
    sa.Column('pesan_kartu_ucapan', sa.Text(), nullable=True),
    sa.Column('total_harga', sa.Float(), nullable=False),
    sa.Column('status_pesanan', sa.String(length=50), nullable=True),
    sa.Column('alamat_pengiriman', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_alamat'], ['address_book.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_pesanan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_pesanan', sa.String(length=36), nullable=False),
    sa.Column('id_produk', sa.String(length=36), nullable=False),
    sa.Column('id_varian', sa.String(length=36), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('request_khusus', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pesanan'], ['pesanan.id'], ),
    sa.ForeignKeyConstraint(['id_produk'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_varian'], ['varian_produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pembayaran',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_pesanan', sa.String(length=36), nullable=False),
    sa.Column('id_transaksi_gateway', sa.String(length=100), nullable=True),
    sa.Column('metode_pembayaran', sa.String(length=50), nullable=True),
    sa.Column('tanggal_bayar', sa.DateTime(), nullable=True),
    sa.Column('jumlah_bayar', sa.Float(), nullable=False),
    sa.Column('bukti_transfer', sa.String(length=255), nullable=True),
    sa.Column('payload_gateway', sa.JSON(), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_pesanan'], ['pesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengiriman',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_pesanan', sa.String(length=36), nullable=False),
    sa.Column('nama_kurir', sa.String(length=100), nullable=True),
    sa.Column('no_resi', sa.String(length=100), nullable=True),
    sa.Column('biaya_ongkir', sa.Float(), nullable=True),
    sa.Column('status_pengiriman', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_pesanan'], ['pesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengiriman')
    op.drop_table('pembayaran')
    op.drop_table('detail_pesanan')
    op.drop_table('pesanan')
    # ### end Alembic commands ###
