"""Menambahkan tabel user dan book

Revision ID: d7ac553a0823
Revises: 
Create Date: 2026-05-16 15:57:59.543485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ac553a0823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('address_book',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nama_kontak', sa.String(length=80), nullable=False),
    sa.Column('label_alamat', sa.String(length=50), nullable=True),
    sa.Column('nama_penerima', sa.String(length=100), nullable=True),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=True),
    sa.Column('alamat_lengkap', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_book')
    op.drop_table('users')
    # ### end Alembic commands ###
