"""Menambahkan tabel kategori dan produk

Revision ID: dda76804e5a4
Revises: d7ac553a0823
Create Date: 2026-05-21 14:02:31.925749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda76804e5a4'
down_revision = 'd7ac553a0823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_kategori', sa.String(length=36), nullable=False),
    sa.Column('nama_produk', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('gambar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galeri_produk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_produk', sa.String(length=36), nullable=False),
    sa.Column('url_gambar', sa.String(length=255), nullable=False),
    sa.Column('is_utama', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_produk'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('varian_produk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_produk', sa.String(length=36), nullable=False),
    sa.Column('nama_varian', sa.String(length=100), nullable=False),
    sa.Column('harga_varian', sa.Float(), nullable=False),
    sa.Column('stok_varian', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_produk'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('varian_produk')
    op.drop_table('galeri_produk')
    op.drop_table('products')
    op.drop_table('kategori')
    # ### end Alembic commands ###
